feat: get session_id
rudderlabs/rudder-sdk-ios pull request #385
Opened 2023-09-08 05:24 UTC by pallabmaiti

# Description

Get `session_id` from Client.

2023-09-08 09:03 UTC, 1abhishekpandey approved these changes

2023-09-08 09:08 UTC, desusai7 approved these changes

2023-09-08 13:24 UTC, 1abhishekpandey requested changes

2023-09-08 13:24 UTC, 1abhishekpandey commented on Sources/Classes/RSClient.m
> +}
This is entering into an infinite loop.

Steps to reproduce it: Just enable lifecycle and run the app.

2023-09-12 05:04 UTC, 1abhishekpandey approved these changes

2023-09-12 05:07 UTC, desusai7 approved these changes

2023-09-12 06:18 UTC, merged