Feature/sdk 1837 support deep linking tracking on ios  implementation
rudderlabs/rudder-sdk-ios pull request #520
Opened 2024-06-11 09:44 UTC by shwetalodhe123

1. code to deep link usingURL Schemes
2. code to read param in URL
3. code to test deep link in swift and objC sample app

2024-06-12 08:49 UTC, shwetalodhe123 commented
1. Remove refName parameter
2. Refactor sample app code
3. Remove stale files

2024-06-12 12:43 UTC, shwetalodhe123 commented
1.remove refAppName param
2.add and modified openURL method for swift
3. Modified code in sample apps
4. removed stale files

2024-06-12 14:16 UTC, shwetalodhe123 commented on Sources/Classes/RSClient.m
> +- (void)openURL:(NSURL *)url options:(NSDictionary *)options
Update Done.

2024-06-12 14:16 UTC, shwetalodhe123 commented on Sources/Classes/RSClient.m
> +}
Update Done

2024-06-12 14:19 UTC, shwetalodhe123 commented
1. add option param in deep link payload

2024-06-12 14:34 UTC, shwetalodhe123 commented on Examples/RudderSampleAppObjC/RudderSampleAppObjC/_AppDelegate.m
> +        [[RSClient sharedInstance]openURL:url options:options];
it will needed when user calls custom method when os is 12.0 or below 12.0
- (void)openURL:(NSURL *)url options:(NSDictionary *)options{
}

2024-06-12 16:10 UTC, 1abhishekpandey requested changes

2024-06-12 16:10 UTC, 1abhishekpandey commented on Sources/Classes/RSClient.m
> +}
In this line `properties[@"options"] = options;`, we are creating another `options` field; instead we can copy the content directly into the properties object. 

Please use the following code snippet. Over here, I've optimised the code and fixed indentation:

```suggestion
- (void)openURL:(NSURL *)url options:(NSDictionary<NSString *,NSObject *> *)options {
    if ([RSClient getOptStatus]) {
        [self reportDiscardedEvent];
        return;
    }
    NSString *urlString = url.absoluteString;
    NSMutableDictionary<NSString *,NSObject *> *properties = [[NSMutableDictionary alloc] init];
    NSArray *paramArray = [RSUtils extractParamFromURL:url];
    if (paramArray.count > 0) {
        // Iterate through the query items
        for (NSURLQueryItem *item in paramArray) {
            [RSLogger logVerbose:[[NSString alloc] initWithFormat:@"Parameter name: %@, value: %@", item.name, item.value]];
            properties[item.name] = item.value;
        }
    }
    if (options != nil) {
        for (NSString *key in options) {
            properties[key] = options[key];
        }
    }
    properties[@"url"] = urlString;
    [self track:@"Deep Link Opened" properties:[properties copy]];
}

- (void)openURL:(NSURL *)url {
    [self openURL:url options:nil];
}
```

2024-06-12 16:10 UTC, 1abhishekpandey commented on Sources/Classes/Headers/Public/RSClient.h
> +- (void)openURL:(NSURL *)url options:(NSDictionary *)options;
Let's add type safety. (You may look at other APIs e.g., track present in this class. We have declared the types for the `NSDictionary` object.)
```suggestion
- (void)openURL:(NSURL *)url options:(NSDictionary<NSString*, id>*)options;
```

2024-06-13 07:21 UTC, shwetalodhe123 commented
Modified method suggested

2024-06-13 08:48 UTC, 1abhishekpandey approved these changes

2024-06-13 10:11 UTC, ChryssaAliferi approved these changes

2024-06-13 10:28 UTC, merged