feat: implement exponential retry mechanism for handling network errors
rudderlabs/rudder-sdk-ios pull request #525
Opened 2024-07-29 07:30 UTC by SKannaniOS

# Description

< Replace with adequate description for this PR>

2024-07-31 09:04 UTC, 1abhishekpandey commented on Sources/Classes/RSCloudModeManager.m
> +
Please add the logic to `reset` the backoff when events are sent successfully:
```
[self-> backOff reset];
```

2024-07-31 12:10 UTC, saikumarrs requested changes

2024-07-31 17:00 UTC, SKannaniOS commented on Sources/Classes/RSExponentialBackOff.m
> +    exponentialDelay = MIN(exponentialDelay, _maximumDelay);
arc4random_uniform - always return the random value from 0 to < upper bound value. To include the calculated delay value, 1 added.

2024-07-31 17:25 UTC, SKannaniOS commented on Sources/Classes/RSCloudModeManager.m
>              if(response == nil) {
As per the RSCloudModeManager code logic, other than "WRONG_WRITE_KEY", every network error code is retryable and no messages are dropped from local DB. So please guide on the logic & what needs to be implemented.

2024-08-01 01:12 UTC, saikumarrs commented on Sources/Classes/RSCloudModeManager.m
>              if(response == nil) {
Here is a simplistic overview:
2XX - success and proceed
5xx and 429 - retry
others - abort and proceed

However, looks like we want to address this in v2 SDKs. So, resolve this thread unless you have any further comments.

2024-08-01 19:03 UTC, SKannaniOS commented on Sources/Classes/RSCloudModeManager.m
>              if(response == nil) {
As per the last discussion, the PR has the implementation of exponential retry mechanism.

2024-08-02 00:24 UTC, saikumarrs approved these changes

2024-08-02 06:40 UTC, ChryssaAliferi approved these changes

2024-08-02 11:14 UTC, 1abhishekpandey approved these changes

2024-08-05 07:43 UTC, merged